version: "3"

services:
  db:
    container_name: uptime-postgres
    image: postgres
    command: -c 'max_connections=800'
    shm_size: 1gb
    restart: always
    env_file: .env
    deploy:
      resources:
        limits:
          memory: 5G
    ports:
      - "5000:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - gateway

networks:
  gateway:
    name: uptime
    external: false
